services:

  ###############################################################################
  ########################     nginx     ########################################
  ###############################################################################

  chess_nginx:
    container_name: chess_nginx
    build:
      context: ./docker/nginx
      dockerfile: nginx.Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - "${NGINX_PORT:-3053}:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./laravel/public:/var/www/html/public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chess_nginx.rule=Host(`chess.localhost`)"
      - "traefik.http.services.chess_nginx.loadbalancer.server.port=80"
      - "traefik.docker.network=webproxy"
    networks:
      - chess_network
      - webproxy


  ###############################################################################
  ########################     php     ##########################################
  ###############################################################################

  chess_php_server:
    build:
      context: ./docker/php
      dockerfile: php.Dockerfile
      target: server
    volumes:
      - ./laravel:/var/www/html:z
    networks:
      - chess_network

  chess_php_worker:
    container_name: chess_php_worker
    build:
      context: ./docker/php
      dockerfile: php.Dockerfile
      target: worker
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      - ./laravel:/var/www/html:z
    networks:
      - chess_network


  ###############################################################################
  ########################     redis     ########################################
  ###############################################################################

#  chess_redis:
#    image: redis
#    volumes:
#      - redis_data:/data
#    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD:-chess-pass}" ]
#    networks:
#      - chess_network
#    environment:
#      - REDIS_PASSWORD=${REDIS_PASSWORD:-chess-pass}



  ###############################################################################
  ########################     postgres     #####################################
  ###############################################################################

  chess_postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-chess-db}
      POSTGRES_USER: ${POSTGRES_USER:-chess-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-chess-pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-3054}:5432"
    networks:
      - chess_network


networks:
  chess_network:
  webproxy:
    external: true

volumes:
  redis_data:
  postgres_data: