volumes:
  chess_db_data:
  chess_redis_data:

services:

  ##################################################
  ################     nginx     ###################
  ##################################################

  chess_nginx:
    container_name: chess_nginx
    hostname: chess_nginx
    image: nginx
    restart: always
    ports:
      - "${DOCKER_NGINX_PORT:-3280}:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html

  #################################################################
  ################     php (workspace/CLI)     ####################
  #################################################################

  chess_laravel_workspace:
    image: p3f/chess-php-workspace:local
    build:
      context: ./docker/php
      dockerfile: php.Dockerfile
      target: workspace
      args:
        - UID=${DOCKER_UID:-1000}
        - GID=${DOCKER_GID:-1000}
    container_name: chess_laravel_workspace
    hostname: chess_laravel_workspace
    restart: unless-stopped
    volumes:
      - ./:/var/www/html # MODIFIÉ: Anciennement ./laravel

  ####################################################################
  ################     php (Laravel server)     ######################
  ####################################################################

  # On ne met pas de container_name, ni hostname ici pour permettre la création de plusieurs instances
  chess_laravel_server:
    image: p3f/chess-php-server:local
    build:
      context: ./docker/php
      dockerfile: php.Dockerfile
      target: server
    restart: unless-stopped
    volumes:
      - ./:/var/www/html

  ####################################################################
  ################     php (Laravel Horizon)     #####################
  ####################################################################

  # Horizon n'est pas toujours nécessaire, donc on le commente par défaut, mais vous pouvez le dé-commenter si besoin.
  # On ne met pas de container_name, ni hostname ici pour permettre la création de plusieurs instances
  #  chess_laravel_horizon:
  #    image: p3f/chess-php-horizon:local
  #    build:
  #      context: ./docker/php
  #      dockerfile: php.Dockerfile
  #      target: server
  #    restart: unless-stopped
  #    volumes:
  #      - ./:/var/www/html
  #    command: php artisan horizon

  #####################################################
  ################     Redis     ######################
  #####################################################

  chess_redis:
    image: redis:7-alpine
    hostname: chess_redis
    container_name: chess_redis
    restart: unless-stopped
    command: redis-server --requirepass ${DOCKER_REDIS_PASSWORD:-please_set_a_strong_password!}
    ports:
      - ${DOCKER_REDIS_PORT:-3279}:6379
    volumes:
      - chess_redis_data:/data

  #####################################################
  ################  PostgresSQL   #####################
  #####################################################

  chess_postgres:
    image: postgres:16-alpine
    hostname: chess_postgres
    container_name: chess_postgres
    restart: unless-stopped
    ports:
      - "${DOCKER_DB_PORT:-3232}:5432"
    volumes:
      - chess_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DOCKER_DB_DATABASE:-laravel}
      POSTGRES_USER: ${DOCKER_DB_USERNAME:-laravel}
      POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD:-please_set_a_strong_password!}
