services:
  chess_nginx:
    image: nginx
    ports:
      - "${NGINX_PORT:-3053}:80"
    volumes:
      - ./nginx.smoke-test.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chess_nginx.rule=Host(`chess.localhost`)"
      - "traefik.http.services.chess_nginx.loadbalancer.server.port=80"
      - "traefik.docker.network=webproxy"
    networks:
      - chess_network
      - webproxy